### ISSUE TITLE
Permission request for usage of some models

### ISSUE THREAD

**Issue by litoj** [Compliance-Addons/Compliance-3D#45]
Hello, I have been working on a semi-3D resource pack with focus on variance and general looks improvements. I realised I am currently using your models+textures for most flowers and also cake models.

I wanted to ask you, if I can use those models in my resourcepack, or should I delete both textures and models from my pack and make my own.

Currently, I plan on getting rid of as many textures as possible (to be compatible with both x32 and x16) that will also involve modifying the models. So in the future I would heavily modify all of the models too (only texture mappings where possible).

**Comment by Juknum** [comment]
Hi,

Yeah you can use the cake models as I made them myself, but for the flowers, you may ask @AlkatreizeGME first as it's the original author for them :p

**Comment by litoj** [comment]
Oh, I also see I am using your cactus (but intend to have a try of my own on it).
Thank you for the swift response. I shall await the decision from @AlkatreizeGME before publishing the pack on Modrinth then.

**Comment by AlkatreizeGME** [comment]
it's ok with me if there's a txt with the credits

**Comment by litoj** [comment]
Ok, thank you very much. I will make sure to link to this "issue" in the readme and mention your names, if that's sufficient.
